-- -- CreateTable
-- CREATE TABLE `dev_direktoris` (
--     `id` INTEGER NOT NULL AUTO_INCREMENT,
--     `username` VARCHAR(100) NOT NULL,
--     `direktori` VARCHAR(250) NULL,
--     `create_by` VARCHAR(20) NOT NULL,
--     `update_by` VARCHAR(20) NULL,
--     `create_at` DATETIME(3) NULL,
--     `update_at` DATETIME(3) NULL,

--     PRIMARY KEY (`id`)
-- ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
